# hyproject.conf

[monitor.internal]
name = "eDP-1"

[monitor.home]
# Prefer model+serial when available. Empty fields ignored.
model = "M27QA"
serial = "0x01010101"

[monitor.work]
model = "LS27D300G"
serial = "H1AK500000"

[profile.home]
when = "internal && home"
monitor.internal = "preferred,0x0,1"
monitor.home = "preferred,-2560x0,1"

[profile.work]
when = "internal && work"
monitor.internal = "preferred,0x0,1"
monitor.work = "preferred,-1920x0,1"

[fallback]
mode = "mirror-internal"
internal = "internal"
